### PR TITLE
Tweaking user and groups to keep files editable locally

### PR DESCRIPTION
**Pull request by bkuhl**
This resolves https://github.com/Realpage/lumen/issues/3

### CODE REVIEW

**Comment by bkuhl** [comment]
Thanks @kyleferguson!

**Comment by kyleferguson** [comment]
:trollface:

**Comment by bkuhl** [comment]
aaaaaannnnnnddddd this MR might be pointless - https://blog.docker.com/2016/03/docker-for-mac-windows-beta/

**Comment by jlaswell** [comment]
:+1: So long as this is still good to merge, @bkuhl ?

**Comment by bkuhl** [comment]
:+1:

**Pull request merged**
